AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  PROJECT:
    Type: String
  ENVIRONMENT:
    Type: String
  DEPLOYMENTBUCKET:
    Type: String
  HOSTEDZONE:
    Type: String
    Description: Root hosted domain name (domain.com)
    Default: geja.se
  IndexDocument:
    Type: String
    Default: index.html
  Certificate:
    Type: String
    Description: ARN to an ACM certificate hosted in us-east-1
    Default: arn:aws:acm:us-east-1:479330620126:certificate/35c98082-94dd-488e-acf3-ffbdf5f206cd

Mappings:
  dev:
    domains:
      api: aws.triplehead.net
      website: dev.geja.se
  prod:
    domains:
      api: api.geja.se
      website: geja.se

Conditions:
  IsProd: !Equals [ !Ref ENVIRONMENT, prod ]

Outputs:
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName

Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${DEPLOYMENTBUCKET}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocument
        ErrorDocument: !Ref IndexDocument

  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadGetObject,
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub ${ContentBucket.Arn}/*

  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - ContentBucket
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !FindInMap [!Ref ENVIRONMENT, domains, website]
        Origins:
          - DomainName: !Sub ${ContentBucket}.s3-website-${AWS::Region}.amazonaws.com
            Id: BucketCustomOrigin
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        # http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationDownloadDist
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: !Join [ "", [ "/", !Ref IndexDocument ] ]
          - ErrorCode: 404
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: !Join [ "", [ "/", !Ref IndexDocument ] ]
        DefaultCacheBehavior:
          TargetOriginId: BucketCustomOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          DefaultTTL: 300
          MinTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: 'TLSv1'
          SslSupportMethod: 'sni-only'

  DistributionDNSAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join [ "", [ !Ref HOSTEDZONE, "." ] ]
      RecordSets:
      - Name: !Join [ "", [ !FindInMap [!Ref ENVIRONMENT, domains, website], "." ] ]
        Type: A
        AliasTarget:
          # When you create alias resource record sets for CloudFront,
          # you must specify Z2FDTNDATAQYW2 for the HostedZoneId property.
          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html#w2ab1c17c23c81c11
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt Distribution.DomainName
