
version: 2
jobs:
  test:
    docker:
      - image: sleavely/node-awscli:10.15
    environment:
      ENVIRONMENT: test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dev-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dev-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy_dev:
    docker:
      - image: sleavely/node-awscli:10.15
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      ENVIRONMENT: dev
      PROJECT: geja
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-dependencies-{{ checksum "package.json" }}
            - dev-dependencies-

      - run: yarn install

      - run: make deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
